version: "3.8"
services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "9000:9000"
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel


networks:
  laravel:
    driver: bridge